---
config:
  layout: dagre
---
flowchart TB
 subgraph Entradas["Origens de Dados"]
        TXT_DUEOF["Files DUEOF 2003-2024"]
        TXT_LIQ["Files Liquidação 2003-2024"]
  end
 subgraph DataLake["Azure Data Lake Storage (ADLS Gen2)"]
    direction TB
        Bronze[("Camada BRONZE Dados Brutos - Ingestão Rápida")]
        Silver[("Camada SILVER Dados Processados - Tabelas Delta/Parquet")]
  end
 subgraph P1["Pipeline ETL - DUEOF"]
        Read_B1["Leitura e .cache 1.4M+ registros"]
        Parse_B1["Parsing de String substring fixo"]
        Filter_B1["Filtro Tipo D Dotação/Empenho"]
  end
 subgraph P2["Pipeline ETL - Liquidação"]
        Read_B2["Leitura .txt"]
        Parse_B2["Parsing de String substring fixo"]
  end
 subgraph Databricks["Azure Databricks (Motor Apache Spark)"]
    direction TB
        P1
        P2
        Join["Processamento Paralelo: Joins e Agregações Agrupamento por Dotação"]
  end
 subgraph Saidas["Saídas e Visualização"]
    direction TB
        CSV_Final["Arquivos CSV Consolidados Final Painel SES-GO"]
        PBI["Power BI Dashboards Visualização Execução Orçamentária"]
  end
    TXT_DUEOF -- Ingestão --> Bronze
    TXT_LIQ -- Ingestão --> Bronze
    Bronze -- PySpark Read --> Read_B1 & Read_B2
    Read_B1 --> Parse_B1
    Parse_B1 --> Filter_B1
    Filter_B1 --> Join
    Read_B2 --> Parse_B2
    Parse_B2 --> Join
    Join -- PySpark Write --> Silver
    Silver -- Coalesce 1 --> CSV_Final
    CSV_Final --> PBI
    Databricks -.-> OutrasSecre["Outras Secretarias Estaduais - Reuso da Estrutura Modular"]
    Silver -.-> OutrasSecre

     Bronze:::storage
     Silver:::storage
     Read_B1:::process
     Parse_B1:::process
     Filter_B1:::process
     Read_B2:::process
     Parse_B2:::process
     Join:::process
     CSV_Final:::storage
     PBI:::visual
     OutrasSecre:::extern
    classDef storage fill:#f9f,stroke:#333,stroke-width:2px,color:black
    classDef process fill:#bbf,stroke:#333,stroke-width:2px,color:black
    classDef visual fill:#dfd,stroke:#333,stroke-width:2px,color:black
    classDef extern fill:#ddd,stroke:#333,stroke-width:1px,stroke-dasharray: 5 5,color:black